# -*- coding: utf-8 -*-
"""midcappython code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mpi58pl3-99VGhnvI4e67A_Uy33HzQ2q
"""

import yfinance as yf
import pandas as pd

# Updated list of mid-cap companies (problematic tickers removed)
mid_cap_tickers = ['PIDILITIND.NS', 'GODREJCP.NS', 'MARICO.NS',
                   'LICHSGFIN.NS', 'BERGEPAINT.NS', 'AUROPHARMA.NS', 'BALKRISIND.NS',
                   'TORNTPHARM.NS', 'BATAINDIA.NS', 'MPHASIS.NS', 'PAGEIND.NS',
                   'CUMMINSIND.NS', 'ASHOKLEY.NS', 'CHOLAFIN.NS', 'PETRONET.NS',
                   'COLPAL.NS', 'LUPIN.NS', 'GLENMARK.NS', 'APOLLOHOSP.NS',
                   'BANKINDIA.NS', 'TVSMOTOR.NS', 'VOLTAS.NS', 'DALBHARAT.NS',
                   'NAM-INDIA.NS', 'WHIRLPOOL.NS', 'ABB.NS', 'CONCOR.NS',
                   'NATIONALUM.NS', 'CASTROLIND.NS', 'OBEROIRLTY.NS', 'HINDPETRO.NS',
                   'JUBLFOOD.NS', 'RAMCOCEM.NS', 'NMDC.NS', 'ESCORTS.NS',
                   'RECLTD.NS', 'MUTHOOTFIN.NS', 'MGL.NS', 'BIOCON.NS',
                   'TRENT.NS', 'IDFCFIRSTB.NS', 'SYNGENE.NS', 'POLYCAB.NS',
                   'ABBOTINDIA.NS', 'MAXHEALTH.NS']

# Initialize an empty list to store the data
mid_cap_data = []

for ticker in mid_cap_tickers:
    # Fetch data
    stock = yf.Ticker(ticker)
    hist = stock.history(period="1d", interval="5m")

    # Get additional information
    info = stock.info
    market_cap = info.get('marketCap', None)
    pe_ratio = info.get('trailingPE', None)
    industry_pe = info.get('industryPE', None)
    debt_to_equity = info.get('debtToEquity', None)
    dividend_yield = info.get('dividendYield', None)
    roe = info.get('returnOnEquity', None) if 'returnOnEquity' in info else None

    # Append data for each time interval
    for time, row in hist.iterrows():
        mid_cap_data.append({
            'Timestamp': time,
            'Stock Name': ticker,
            'Open': row['Open'],
            'High': row['High'],
            'Low': row['Low'],
            'Close': row['Close'],
            'Volume': row['Volume'],
            'Market Cap': market_cap,
            'PE Ratio': pe_ratio,
            'Industry PE': industry_pe,
            'Debt to Equity': debt_to_equity,
            'Dividend Yield': dividend_yield,
            'ROE': roe
        })

# Convert the list to a DataFrame
mid_cap_df = pd.DataFrame(mid_cap_data)

# Save to CSV
mid_cap_df.to_csv("/home/sushantswarup00/ETL_PROJECT/SOURCE_FILES/mid_cap_companies_Minutes_data.csv", index=False)

print("Mid-cap companies CSV file created successfully.")